version: '3.5'
services:
  admin-ui:
    container_name: admin_ui
    image: epr3/schoolar-admin-ui:latest
  user-ui:
    container_name: user_ui
    image: epr3/schoolar-user-ui:latest

networks:
  default:
    external:
      name: schoolar-network