version: '3.5'
services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  php-queue-service:
    build:
      dockerfile: Dockerfile-queue
      context: ./quiz-service
    restart: on-failure
    volumes:
      - ./quiz-service:/quiz-app
    links:
      - redis
      - db
    depends_on:
      - redis
      - db
    tty: true
  php-service:
    build:
      dockerfile: Dockerfile
      context: ./quiz-service
    restart: on-failure
    volumes:
      - ./quiz-service:/quiz-app
    links:
      - db
    depends_on:
      - db
    tty: true
    ports:
      - "8000:8000"
  node-service:
    build: ./node-service
    restart: on-failure
    volumes:
      - ./node-service:/node-app
      - /node-app/node_modules
    links:
      - redis
      - db
    depends_on:
      - redis
      - db
    tty: true
    ports:
      - "3000:3000"
volumes:
  redis_data:
