version: '3.5'
services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  nginx:
    build: .
    container_name: nginx
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - 80:80
volumes:
  redis_data:

networks:
  default:
    name: schoolar-network

