version: '3.5'
services:
  schedule-service:
    container_name: schedule_service
    image: epr3/schoolar-schedule-service:latest
    command: "/usr/bin/supervisord"
    environment:
      - APP_NAME=Lumen
      - APP_ENV=production
      - APP_URL=http://localhost
      - APP_TIMEZONE=UTC
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/database/db.sqlite
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      - JWT_SECRET=123456

networks:
  default:
    external:
      name: schoolar-network